config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    resources :questions, shallow: true, only: :index

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true
      end
    end

    resources :gists, only: :index

    resources :badges do
      resources :badge_rules, as: :rule, path: :rules, except: %i[index show]
    end

  end

  resources :feedbacks, only: %i[new create]

  resources :badges, only: :index

end

app/models/admin.rb
class Admin < User

  validates :first_name, presence: true
  validates :last_name, presence: true

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :validate_question_answers

  scope :correct, -> { where(correct: true)}

  private

  def validate_question_answers
    errors.add(:answers) if question.answers.count >= 4
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_and_belongs_to_many :users
  has_one :rule, class_name: 'BadgeRule', dependent: :destroy

  validates :name, presence: true
  validates :image, presence: true
end

app/models/badge_rule.rb
class BadgeRule < ApplicationRecord
  RULE_TYPES = %w[category first_try level]

  belongs_to :badge

  validates :rule_type, presence: true
  validates :rule_value, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests

  default_scope { order(title: :asc) }

  def self.list
    select(:title)
  end

end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user

  validates :message, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true

end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages, dependent: :destroy
  belongs_to :author, class_name: 'User'

  validates :title, presence: true, uniqueness: { scope: :level }
  validates :level, numericality: {only_integer: true}

  scope :easy, -> { where(level: 0..1) }
  scope :medium, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }

  scope :category_tests, -> (title) { joins(:category)
                                     .where(categories: { title: title }) }

  scope :questions_tests, -> { where(test_passages).order(questions.body) }


  def self.category_title(title)
    category_tests(title).order(title: :desc).pluck(:title)
  end


  def self.levels
    select(:level).distinct
  end

end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_validation :set_next_question, on: :update

  SUCCESS_SCORE = 85

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions +=1
    end

    save!
  end

  def success?
    score > SUCCESS_SCORE
  end

  def timeaut
    self.created_at + test.timer <= Time.now
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def set_next_question
    self.current_question = next_question
  end

  def score
    (correct_questions / self.test.questions.count) * 100
  end

end

app/models/test_user.rb
class TestsUser < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/models/tests_user.rb
class TestsUser < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :confirmable,
         :trackable

  has_many :gists, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages, dependent: :destroy
  has_many :author_tests, class_name: 'Test', foreign_key: 'author_id', dependent: :destroy
  has_many :feedbacks
  has_and_belongs_to_many :badges

  validates :email, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }


  def passed_tests_level(level)
    tests.where(level: level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    is_a?(Admin)
  end


end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController

  before_action :find_admin_badge, only: %i[show edit update destroy]

  def index
    @admin_badges = Badge.all
  end

  def show
    @rule_types = BadgeRule::RULE_TYPES
  end

  def new
    @admin_badge = Badge.new
  end

  def edit; end

  def create
    @admin_badge = Badge.new(admin_badge_params)

    if @admin_badge.save
      redirect_to admin_badge_path(@admin_badge), notice: I18n.t('.created')
    else
      render :new
    end
  end

  def update
    if @admin_badge.update(admin_badge_params)
      redirect_to admin_badges_path, notice: I18n.t('.updated')
    else
      render :edit
    end
  end

  def destroy
    @admin_badge.destroy
    redirect_to admin_badges_path, notice: I18n.t('.destroyed')
  end

  private

  def find_admin_badge
    @admin_badge = Badge.find(params[:id])
  end

  def admin_badge_params
    params.require(:badge).permit(:name, :image)
  end

end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
    @badges = current_user.badges
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  MESSAGE = { 'notice': 'alert alert-info', 'success': 'alert alert-success',
              'error': 'alert alert-danger', 'alert': 'alert alert-warning' }

  def flash_class(level)
    MESSAGE[level.to_sym]
  end

end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/flash_helper.rb
module FlashHelper
  def flash_helper
    if flash[:alert]
      render inline: "<%= content_tag :p, flash[:alert], class: 'flash alert'  %>"
    end
  end
end

app/helpers/footer_helper.rb
module FooterHelper
  def github_url(author, repo)
    link_to 'TestGuru', "https://github.com/#{author+'/'+repo}", target: '_blank', rel: 'nofollow'
  end

  def current_year
    Time.now.year
  end
end

app/helpers/gists_helper.rb
module GistsHelper

  def gist_url(name, id, options = {})
    link_to name, "https://gist.github.com/#{id}", options
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.persisted?
      "Edit #{@question.test.title} Question"
    else
      "Create New #{@test.title} Question"
    end
  end
end

app/helpers/tests_helper.rb
module TestsHelper
  TEST_LEVELS = { 1 => :easy, 2 => :elementary, 3 => :advanced, 4 => :hard }
  def test_level(test)
    TEST_LEVELS[test.level] || :hero
  end
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td><%= badge.name %></td>
  <td><%= image_tag badge.image, size: 30 %></td>
  <td><%= link_to t('other.show'), admin_badge_path(badge) %></td>
  <td><%= link_to t('other.edit'), edit_admin_badge_path(badge) %></td>
  <td><%= link_to t('other.delete'),
                  admin_badge_path(badge),
                  method: :delete,
                  data: { confirm: t('other.confirm') } %>
  </td>
</tr>

app/views/admin/badges/_form.html.erb
<%= form_with(model: [:admin, @admin_badge], local: true) do |f| %>
  <%= render 'shared/errors', resource: @admin_badge %>

  <div class="form-group col-4">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group col-4">
    <%= f.label :image %>
    <%= f.text_field :image, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/badges/edit.html.erb
<h1><%= t('.header') %></h1>

<%= render 'form', admin_badge: @admin_badge %>

app/views/admin/badges/index.html.erb
<h1><%= t('.header') %></h1>

<p><%= link_to t('other.create'), new_admin_badge_path, class: 'btn btn-outline-primary' %></p>

<table class="table table-hover">
  <thead>
  <tr>
    <th><%= t('badges.index.name') %></th>
    <th><%= t('badges.index.image') %></th>
    <th colspan="3"><%= t('other.action') %></th>
  </tr>
  </thead>
  <tbody>
  <%= render @admin_badges %>
  </tbody>
</table>

app/views/admin/badges/new.html.erb
<h1><%= t('.header') %></h1>

<%= render 'form', admin_badge: @admin_badge %>

app/views/admin/badges/show.html.erb
<h1><%= @admin_badge.name %></h1>

<p><%= image_tag @admin_badge.image, size: 60 %></p>

<h3><%= t('.rule') %></h3>
<% if @admin_badge.rule.nil? %>
  <div class="btn-group" role="group">
    <% @rule_types.each do |rule| %>
      <%= link_to rule, new_admin_badge_rule_path(@admin_badge, badge_rule: { rule_type: rule }), class: 'btn btn-primary' %>
    <% end %>
  </div>
<% else %>
  <%= link_to @admin_badge.rule.rule_type, edit_admin_badge_rule_path(@admin_badge, @admin_badge.rule), class: 'btn btn-primary' %>
  <%= link_to t('other.delete'), admin_badge_rule_path(@admin_badge, @admin_badge.rule), method: :delete, data: { confirm: t('other.confirm') }, class: 'btn btn-danger' %>
<% end %>

app/views/badges/_badgre.html.erb
<tr>
  <td><%= badge.name %></td>
  <td><%= image_tag badge.image, size: 30 %></td>
</tr>

app/views/badges/index.html.erb
<h1><%= t('.header') %></h1>

<table class="table table-hover">
  <thead>
  <tr>
    <th><%= t('.name') %></th>
    <th><%= t('.image') %></th>
  </tr>
  </thead>
  <tbody>
  <%= render @badges %>
  </tbody>
</table>