config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    resources :questions, shallow: true, only: :index

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true
      end
    end

    resources :gists, only: :index

    resources :badges do
      resources :badge_rules, as: :rule, path: :rules, except: %i[index show]
    end

  end

  resources :feedbacks, only: %i[new create]

  resources :badges, only: :index

end

app/models/admin.rb
class Admin < User

  validates :first_name, presence: true
  validates :last_name, presence: true

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :validate_question_answers

  scope :correct, -> { where(correct: true)}

  private

  def validate_question_answers
    errors.add(:answers) if question.answers.count >= 4
  end

end

app/models/badge.rb
class Badge < ApplicationRecord
  has_and_belongs_to_many :users
  has_one :rule, class_name: 'BadgeRule', dependent: :destroy

  validates :name, presence: true
  validates :image, presence: true
end

app/models/badge_rule.rb
class BadgeRule < ApplicationRecord
  RULE_TYPES = %w[category first_try level]

  belongs_to :badge

  validates :rule_type, presence: true
  validates :rule_value, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests

  default_scope { order(title: :asc) }

  def self.list
    select(:title)
  end

end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user

  validates :message, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true

end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages, dependent: :destroy
  belongs_to :author, class_name: 'User'

  validates :title, presence: true, uniqueness: { scope: :level }
  validates :level, numericality: {only_integer: true}

  scope :easy, -> { where(level: 0..1) }
  scope :medium, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }

  scope :category_tests, -> (title) { joins(:category)
                                     .where(categories: { title: title }) }

  scope :questions_tests, -> { where(test_passages).order(questions.body) }


  def self.category_title(title)
    category_tests(title).order(title: :desc).pluck(:title)
  end


  def self.levels
    select(:level).distinct
  end

end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_validation :set_next_question, on: :update

  SUCCESS_SCORE = 85

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions +=1
    end

    save!
  end

  def success?
    score > SUCCESS_SCORE
  end

  def timeaut
    self.created_at + test.timer <= Time.now
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def set_next_question
    self.current_question = next_question
  end

  def score
    (correct_questions / self.test.questions.count) * 100
  end

end

app/models/test_user.rb
class TestsUser < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/models/tests_user.rb
class TestsUser < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :confirmable,
         :trackable

  has_many :gists, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages, dependent: :destroy
  has_many :author_tests, class_name: 'Test', foreign_key: 'author_id', dependent: :destroy
  has_many :feedbacks
  has_and_belongs_to_many :badges

  validates :email, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }


  def passed_tests_level(level)
    tests.where(level: level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    is_a?(Admin)
  end


end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/flash_helper.rb
module FlashHelper
  def flash_helper
    if flash[:alert]
      render inline: "<%= content_tag :p, flash[:alert], class: 'flash alert'  %>"
    end
  end
end

app/helpers/footer_helper.rb
module FooterHelper
  def github_url(author, repo)
    link_to 'TestGuru', "https://github.com/#{author+'/'+repo}", target: '_blank', rel: 'nofollow'
  end

  def current_year
    Time.now.year
  end
end

app/helpers/gists_helper.rb
module GistsHelper

  def gist_url(name, id, options = {})
    link_to name, "https://gist.github.com/#{id}", options
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.persisted?
      "Edit #{@question.test.title} Question"
    else
      "Create New #{@test.title} Question"
    end
  end
end

app/helpers/tests_helper.rb
module TestsHelper
  TEST_LEVELS = { 1 => :easy, 2 => :elementary, 3 => :advanced, 4 => :hard }
  def test_level(test)
    TEST_LEVELS[test.level] || :hero
  end
end

app/views/admin/_nav.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>
  <%= link_to t('nav.badges'), admin_badges_path, class: 'navbar-brand' %>
  <span class="navbar-brand"> <%= t('admin.nav') %> </span>

  <span class="navbar-text">
    <% if user_signed_in? %>
      Welcome, <b><%= current_user.email %></b> Guru |
      <%= link_to 'logout', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Log in", new_session_path(resource_name) %> |
      <%= link_to "Sign up", new_registration_path(resource_name) %>

    <% end %>
  </span>
</nav>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>

    <h2><%= t('.header', count: resource.errors.count) %>:</h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <%  end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>">
    <%= value %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="conteiner-fluid">
  <div class="conteiner">
    <div class="row-padding text-center">
      <div class="col-12">

        <p><%= github_url('GitHubLoad', 'TestGuru') %> -  проект Дмитрия Леденёва. <%= current_year %></p>

        <p><%= link_to "Учебный проект в онлайн-школе Thinknetica", "http://thinknetica.com/", target: "_blank", rel: "nofollow" %></p>

      </div>
    </div>
  </div>
</footer>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>
  <%= link_to t('.feedback'), new_feedback_path, class: 'navbar-brand' %>
  <%= link_to t('.badges'), badges_path, class: 'navbar-brand' %>
  <% if user_signed_in? && current_user.admin? %>
   <%= link_to t('admin.nav'), admin_tests_path, class: 'navbar-brand' %>
  <% end %>


  <span class="navbar-text">
    <% if user_signed_in? %>
      Welcome, <b><%= current_user.email %></b> Guru |
      <%= link_to 'logout', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Log in", new_session_path(resource_name) %> |
      <%= link_to "Sign up", new_registration_path(resource_name) %>

    <% end %>
  </span>
</nav>